[nginx]
13.38.70.128 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/platformalert

[app]
10.0.2.84 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/platformalert ansible_ssh_common_args='-o ProxyJump=bastion'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
